In [ ]:
from google.colab import files
uploaded = files.upload()

Saving master_dataset.csv to master_dataset.csv
Saving products_dataset.csv to products_dataset.csv

In [ ]:
import pandas as pd

master = pd.read_csv('master_dataset.csv')
product = pd.read_csv('products_dataset.csv')

master.shape , product.shape
master.head()
product.head()

master.info()
product.info()

master.columns.tolist()
product.columns.tolist()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3552 entries, 0 to 3551
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           3552 non-null   object
 1   order_id       3552 non-null   object
 2   product_id     3552 non-null   object
 3   customer_no    3445 non-null   object
 4   quantity       3446 non-null   float64
 5   sales_channel  3446 non-null   object
 6   total_bill     3552 non-null   float64
dtypes: float64(2), object(5)
memory usage: 194.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160 entries, 0 to 159
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   product_id        160 non-null    object
 1   product_price     146 non-null    float64
 2   product_category  152 non-null    object
dtypes: float64(1), object(2)
memory usage: 3.9+ KB

['product_id', 'product_price', 'product_category']

In [ ]:
print(master.isnull().sum())
print(master.duplicated().sum())
print(master.describe())
print(master['sales_channel'].unique())
print(master['product_id'].dtype)

date               0
order_id           0
product_id         0
customer_no      107
quantity         106
sales_channel    106
total_bill         0
dtype: int64
45
          quantity     total_bill
count  3446.000000    3552.000000
mean      5.304991    7466.989209
std       3.234630   13814.962714
min     -10.000000      32.150000
25%       3.000000     924.900000
50%       5.000000    2528.700000
75%       8.000000    7706.580000
max      10.000000  139102.300000
[' Online ' nan 'Online' 'In-store' 'in-store' 'IN-STORE' 'online'
 ' In-store ' 'In store' 'ONLINE']
object

In [ ]:
print(product.isnull().sum())
print(product.duplicated().sum())
print(product.describe())
print(product['product_category'].unique())
print(product['product_id'].dtype)

product_id           0
product_price       14
product_category     8
dtype: int64
0
       product_price
count     146.000000
mean     1236.397603
std      1874.873831
min        32.150000
25%       186.552500
50%       471.465000
75%      1557.652500
max     12539.430000
['Hardware' ' Dairy ' 'BAKERY' nan 'Cleaning Supplies' ' Stationery '
 'Footwear' 'Food and Drinks' 'TOYS' 'BABY CARE' 'Kitchen Appliances'
 'Personal Care' 'clothing' 'gardening' 'Baby Care' 'cleaning supplies'
 ' Pet Supplies ' 'Bakery' 'Dairy' 'Electronics' 'frozen foods'
 'Stationery' 'Frozen Foods' 'FOOD AND DRINKS' 'Health and Wellness'
 'Snacks' 'Gardening' ' Kitchen Appliances ' 'Pet Supplies' 'FOOTWEAR'
 'food and drinks' 'Beverages' ' Gardening ' 'toys' 'PERSONAL CARE'
 ' Food and Drinks ' 'SNACKS' 'snacks' ' Personal Care ' ' Electronics '
 ' Health and Wellness ' 'HEALTH AND WELLNESS' 'Food & Drinks' 'Toys'
 ' Home Decor ' 'bakery' ' Toys ' 'Clothing' 'Home Decor' 'electronics'
 'Health & Wellness' 'beverages' 'CLOTHING']
object

In [ ]:
missing_ids = set(master['product_id']) - set(product['product_id'])
len(missing_ids)

23

In [ ]:
master[master.duplicated(keep=False)].sort_values(by='order_id')

,date,order_id,product_id,customer_no,quantity,sales_channel,total_bill
3011,11-11-2024,ORD00034,P0138,9327059683,8.0,Online,10225.84
214,11-11-2024,ORD00034,P0138,9327059683,8.0,Online,10225.84
970,2024-12-09,ORD00081,P0027,9683935600,3.0,Online,197.94
1816,2024-12-09,ORD00081,P0027,9683935600,3.0,Online,197.94
3008,2024/05/16,ORD00088,P0141,6562697526,5.0,Online,11704.10
...,...,...,...,...,...,...,...
315,2024-01-30,ORD03015,P0027,9715864998,5.0,online,329.90
772,30-07-2024,ORD03050,P0048,9641723276,9.0,Online,2934.81
3433,30-07-2024,ORD03050,P0048,9641723276,9.0,Online,2934.81
1029,20-01-2024,ORD03138,P0037,9871997268,2.0,In-store,1037.18
1441,20-01-2024,ORD03138,P0037,9871997268,2.0,In-store,1037.18

In [ ]:
master[master.duplicated(keep=False)].sort_values(by='order_id').head(20)

,date,order_id,product_id,customer_no,quantity,sales_channel,total_bill
3011,11-11-2024,ORD00034,P0138,9327059683,8.0,Online,10225.84
214,11-11-2024,ORD00034,P0138,9327059683,8.0,Online,10225.84
970,2024-12-09,ORD00081,P0027,9683935600,3.0,Online,197.94
1816,2024-12-09,ORD00081,P0027,9683935600,3.0,Online,197.94
3008,2024/05/16,ORD00088,P0141,6562697526,5.0,Online,11704.10
867,2024/05/16,ORD00088,P0141,6562697526,5.0,Online,11704.10
2924,23 Aug 2024,ORD00118,P0066,8864059081,1.0,Online,231.58
3423,23 Aug 2024,ORD00118,P0066,8864059081,1.0,Online,231.58
1668,01-13-2024,ORD00138,P0159,9797759723,9.0,Online,22914.09
3158,01-13-2024,ORD00138,P0159,9797759723,9.0,Online,22914.09
2305,2024-02-10,ORD00273,P0111,8587517187,3.0,Online,903.93
520,2024-02-10,ORD00273,P0111,8587517187,3.0,Online,903.93
2802,15-10-2024,ORD00387,P0029,6265248799,9.0,NaN,46833.03
818,15-10-2024,ORD00387,P0029,6265248799,9.0,NaN,46833.03
881,05-09-2024,ORD00524,P0035,6838070464,7.0,online,1231.44
491,05-09-2024,ORD00524,P0035,6838070464,7.0,online,1231.44
3042,2024-10-07,ORD00549,P0148,NaN,10.0,Online,1304.20
168,2024-10-07,ORD00549,P0148,NaN,10.0,Online,1304.20
2419,2024-08-04,ORD00579,P0103,6354024760,9.0,IN-STORE,4539.78
3438,2024-08-04,ORD00579,P0103,6354024760,9.0,IN-STORE,4539.78

In [ ]:
master = master.drop_duplicates()
print(master.shape)

(3507, 7)

In [ ]:
master[master['quantity'].isnull()].index.intersection(master[master['sales_channel'].isnull()].index)

Index([2409, 2899, 2918, 3060, 3412], dtype='int64')

In [ ]:
master = master[master['quantity'] >= 0]
print(master.shape)

(3332, 7)

In [ ]:
master['sales_channel'] = master['sales_channel'].str.strip().str.lower()
master['sales_channel'] = master['sales_channel'].replace({
    'in store': 'in-store'
})
master['sales_channel'].unique()

array(['online', nan, 'in-store'], dtype=object)

In [ ]:
product.isnull().sum()

product_id           0
product_price       14
product_category     8
dtype: int64

In [ ]:
product.duplicated().sum()

np.int64(0)

In [ ]:
product.describe()

       product_price
count     146.000000
mean     1236.397603
std      1874.873831
min        32.150000
25%       186.552500
50%       471.465000
75%      1557.652500
max     12539.430000

In [ ]:
product['product_category'].unique()

array(['Hardware', ' Dairy ', 'BAKERY', nan, 'Cleaning Supplies',
       ' Stationery ', 'Footwear', 'Food and Drinks', 'TOYS', 'BABY CARE',
       'Kitchen Appliances', 'Personal Care', 'clothing', 'gardening',
       'Baby Care', 'cleaning supplies', ' Pet Supplies ', 'Bakery',
       'Dairy', 'Electronics', 'frozen foods', 'Stationery',
       'Frozen Foods', 'FOOD AND DRINKS', 'Health and Wellness', 'Snacks',
       'Gardening', ' Kitchen Appliances ', 'Pet Supplies', 'FOOTWEAR',
       'food and drinks', 'Beverages', ' Gardening ', 'toys',
       'PERSONAL CARE', ' Food and Drinks ', 'SNACKS', 'snacks',
       ' Personal Care ', ' Electronics ', ' Health and Wellness ',
       'HEALTH AND WELLNESS', 'Food & Drinks', 'Toys', ' Home Decor ',
       'bakery', ' Toys ', 'Clothing', 'Home Decor', 'electronics',
       'Health & Wellness', 'beverages', 'CLOTHING'], dtype=object)

In [ ]:
product['product_id'].dtype

dtype('O')

In [ ]:
product['product_category'] = product['product_category'].fillna('Unknown')
product['product_price'] = product['product_price'].fillna(product['product_price'].median())

In [ ]:
product['product_category'] = product['product_category'].str.strip().str.lower()

product['product_category'] = product['product_category'].replace({
    'food & drinks': 'food and drinks',
    'health & wellness': 'health and wellness'
})

product['product_category'].unique()

array(['hardware', 'dairy', 'bakery', 'unknown', 'cleaning supplies',
       'stationery', 'footwear', 'food and drinks', 'toys', 'baby care',
       'kitchen appliances', 'personal care', 'clothing', 'gardening',
       'pet supplies', 'electronics', 'frozen foods',
       'health and wellness', 'snacks', 'beverages', 'home decor'],
      dtype=object)

In [ ]:
master['sales_channel'] = master['sales_channel'].str.strip().str.lower()
master['sales_channel'] = master['sales_channel'].replace({'in store': 'in-store'})
master['sales_channel'].unique()

array(['online', nan, 'in-store'], dtype=object)

In [ ]:
merged = master.merge(product, on='product_id', how='left')
print(merged.shape)
merged.isnull().sum()

(3332, 9)

date                  0
order_id              0
product_id            0
customer_no         103
quantity              0
sales_channel        99
total_bill            0
product_price        67
product_category     67
dtype: int64

In [ ]:
merged['product_category'] = merged['product_category'].fillna('unmatched')
merged['product_price'] = merged['product_price'].fillna('unmatched')

In [ ]:
merged[merged['product_category'] != 'unmatched']

,date,order_id,product_id,customer_no,quantity,sales_channel,total_bill,product_price,product_category
0,2024-01-27,ORD03489,P0133,8515223769,2.0,online,1068.96,534.48,frozen foods
1,2024-07-22,ORD02654,P0060,7920216694,6.0,NaN,985.32,164.22,food and drinks
2,15-11-2024,ORD03170,P0081,8505892306,8.0,online,13120.80,1640.1,footwear
3,2024/09/06,ORD00545,P0084,8499480048,1.0,in-store,6337.34,6337.34,kitchen appliances
4,25-02-2024,ORD02889,P0060,NaN,5.0,online,821.10,164.22,food and drinks
...,...,...,...,...,...,...,...,...,...
3327,2024-07-30,ORD01769,P0143,9845147527,8.0,online,23098.40,2887.3,clothing
3328,28-10-2024,ORD01738,P0012,8110860631,1.0,online,1288.61,471.465,kitchen appliances
3329,2024-10-16,ORD03241,P0122,6271119796,1.0,online,485.00,485.0,health and wellness
3330,07-02-2024,ORD03108,P0053,8127190829,4.0,in-store,739.92,184.98,snacks
3331,26-10-2024,ORD00642,P0060,6685583357,2.0,in-store,328.44,164.22,food and drinks

In [ ]:
merged['sales_channel'] = merged['sales_channel'].fillna('unknown')

In [ ]:
merged.isnull().sum()

date                  0
order_id              0
product_id            0
customer_no         103
quantity              0
sales_channel         0
total_bill            0
product_price         0
product_category      0
dtype: int64

**Analysis**

In [ ]:
merged.groupby('product_category')['total_bill'].sum().sort_values(ascending=False)

product_category
electronics            7221061.93
footwear               3519224.37
kitchen appliances     2904852.90
hardware               2154169.26
clothing               1812761.81
health and wellness     827043.78
home decor              806918.35
toys                    764114.26
gardening               673473.85
unknown                 635013.89
baby care               511985.62
pet supplies            436512.49
cleaning supplies       407086.60
unmatched               372646.68
personal care           333437.83
bakery                  304957.38
frozen foods            269692.92
food and drinks         264131.06
stationery              202798.90
snacks                  138814.22
dairy                   120254.68
beverages                87564.74
Name: total_bill, dtype: float64

In [ ]:
merged['date'].dtype

dtype('O')

In [ ]:
merged['date'].sample(20)

547      03-09-2024
3251     2024-09-24
714     12 Jun 2024
2577     08-18-2024
987      2024-11-20
1646    07 Jul 2024
2324     2024-07-06
1101     2024-11-10
542      2024/08/03
1428     11-11-2024
464      2024-05-23
1454     20-09-2024
1035     03-20-2024
1811     2024/07/14
1139    03 May 2024
2718     2024-08-04
236      2024/08/20
2009     2024/08/06
716      31-08-2024
2927     2024/08/02
Name: date, dtype: object

In [ ]:
merged['date'] = pd.to_datetime(merged['date'], format='mixed', dayfirst=True)

In [ ]:
merged['date'].dtype

dtype('<M8[ns]')

In [ ]:
merged['month'] = merged['date'].dt.month

In [ ]:
merged['month'] = merged['date'].dt.month
merged.groupby('month')['total_bill'].sum()

month
1     2209169.04
2     2054164.97
3     2593320.29
4     1930119.86
5     2044364.22
6     2020201.46
7     1815944.65
8     2358507.54
9     2027776.50
10    1689321.89
11    1762351.93
12    2263275.17
Name: total_bill, dtype: float64

In [ ]:
merged['date'].dt.year.unique()

array([2024], dtype=int32)

In [ ]:
merged.groupby('sales_channel')['total_bill'].sum()

sales_channel
in-store    11951913.00
online      12173983.42
unknown       642621.10
Name: total_bill, dtype: float64

In [ ]:
merged.groupby('product_id')['quantity'].sum().sort_values(ascending=False).head(10)

product_id
P0088    179.0
P0022    175.0
P0126    168.0
P0096    163.0
P0008    163.0
P0030    160.0
P0117    155.0
P0032    155.0
P0055    154.0
P0110    154.0
Name: quantity, dtype: float64

In [ ]:
product.columns.tolist()

['product_id', 'product_price', 'product_category']

In [ ]:
top10 = merged.groupby('product_id')['quantity'].sum().sort_values(ascending=False).head(10)
top10_df = top10.reset_index().merge(product[['product_id', 'product_category']], on='product_id', how='left')
top10_df

  product_id  quantity     product_category
0      P0088     179.0  health and wellness
1      P0022     175.0             footwear
2      P0126     168.0             clothing
3      P0096     163.0  health and wellness
4      P0008     163.0             footwear
5      P0030     160.0            baby care
6      P0117     155.0           stationery
7      P0032     155.0               bakery
8      P0055     154.0        personal care
9      P0110     154.0    cleaning supplies

In [ ]:
bottom10 = merged.groupby('product_id')['quantity'].sum().sort_values(ascending=True).head(10)
bottom10_df = bottom10.reset_index().merge(product[['product_id', 'product_category']], on='product_id', how='left')
bottom10_df

  product_id  quantity product_category
0      P9021       1.0              NaN
1      P9009       6.0              NaN
2      P9015       8.0              NaN
3      P9016       8.0              NaN
4      P9022       8.0              NaN
5      P9010      10.0              NaN
6      P9006      11.0              NaN
7      P9013      12.0              NaN
8      P9017      14.0              NaN
9      P9003      15.0              NaN

In [ ]:
merged[merged['product_id'].str.startswith('P9')]['product_category'].unique()

array(['unmatched'], dtype=object)

In [ ]:
merged[merged['product_category'] != 'unmatched'].groupby('product_id')['quantity'].sum().sort_values(ascending=True).head(10)

product_id
P0066    42.0
P0070    58.0
P0136    65.0
P0002    66.0
P0089    66.0
P0107    67.0
P0071    69.0
P0013    69.0
P0001    71.0
P0123    72.0
Name: quantity, dtype: float64

In [ ]:
bottom10_real = merged[merged['product_category'] != 'unmatched'].groupby('product_id')['quantity'].sum().sort_values(ascending=True).head(10)
bottom10_real_df = bottom10_real.reset_index().merge(product[['product_id', 'product_category']], on='product_id', how='left')
bottom10_real_df

  product_id  quantity     product_category
0      P0066      42.0               snacks
1      P0070      58.0        personal care
2      P0136      65.0              unknown
3      P0002      66.0                dairy
4      P0089      66.0               bakery
5      P0107      67.0              unknown
6      P0071      69.0               bakery
7      P0013      69.0              unknown
8      P0001      71.0             hardware
9      P0123      72.0  health and wellness

In [ ]:
merged[merged['product_category'] != 'unmatched'].groupby('product_id')['total_bill'].sum().sort_values(ascending=False).head(10)

product_id
P0137    1567428.75
P0074    1535689.39
P0118    1216039.46
P0077     930823.74
P0084     915111.90
P0067     894804.22
P0044     674493.51
P0029     602584.99
P0128     516478.03
P0102     493693.08
Name: total_bill, dtype: float64

In [ ]:
merged[merged['product_category'] != 'unmatched'].groupby('product_id')['total_bill'].sum().sort_values(ascending=True).head(10)

product_id
P0160    2874.21
P0070    4218.57
P0129    4496.61
P0149    4933.55
P0080    5166.62
P0009    5532.88
P0004    6923.36
P0056    7245.52
P0033    7323.16
P0104    8064.29
Name: total_bill, dtype: float64

**KPI**

In [ ]:
total_revenue = merged['total_bill'].sum()
print("Total Revenue:", total_revenue)

revenue_by_category = merged.groupby('product_category')['total_bill'].sum().sort_values(ascending=False)
print(revenue_by_category)

revenue_by_channel = merged.groupby('sales_channel')['total_bill'].sum()
print(revenue_by_channel)

aov = merged['total_bill'].sum() / merged['order_id'].nunique()
print("Average Order Value:", aov)

data_quality_rate = (merged['product_category'] != 'unmatched').mean() * 100
print("Data Quality Rate (%):", data_quality_rate)

Total Revenue: 24768517.52
product_category
electronics            7221061.93
footwear               3519224.37
kitchen appliances     2904852.90
hardware               2154169.26
clothing               1812761.81
health and wellness     827043.78
home decor              806918.35
toys                    764114.26
gardening               673473.85
unknown                 635013.89
baby care               511985.62
pet supplies            436512.49
cleaning supplies       407086.60
unmatched               372646.68
personal care           333437.83
bakery                  304957.38
frozen foods            269692.92
food and drinks         264131.06
stationery              202798.90
snacks                  138814.22
dairy                   120254.68
beverages                87564.74
Name: total_bill, dtype: float64
sales_channel
in-store    11951913.00
online      12173983.42
unknown       642621.10
Name: total_bill, dtype: float64
Average Order Value: 7449.178201503759
Data Quality Rate (%): 97.98919567827132

In [ ]:
merged['order_id'].duplicated().sum()

np.int64(7)

In [ ]:
merged.to_csv('cleaned_merged_data.csv', index=False)

In [ ]:
pd.to_numeric(merged['product_price'], errors='coerce').isnull().sum()

np.int64(67)